version: '3'
services:
  nginx:
    container_name: nginx-server
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html
      - ./ssl/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./ssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    networks:
      nginx_server_network:
        ipv4_address: 172.30.0.2
  mitm:
    container_name: mitm
    image: mitm
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./scapyTLS.py:/home/mitm/scapyTLS.py:ro
      - ./startup.sh:/home/mitm/startup.sh
    command: ["sh", "-c", "/home/mitm/startup.sh"]
    networks:
      nginx_server_network:
        ipv4_address: 172.30.0.3

networks:
  nginx_server_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/28
